### ISSUE TITLE
Error behavior

### ISSUE THREAD

**Issue by RiskoZS** [truemedian/luvit-api-design#5]
Yet another thing that could be thought about and standardized. Luvit 2.x is a mix of "throw an error" (`json`, `coro-http`) and "return an assertable tuple" (`fs`). This isn't probably as important as other things, but... thoughts?

As of this writing, of note is the `fs` module proposal: it doesn't indicate that its functions can return a `nil, string`, which makes it look like they are expected to throw an error. Is this intentional, or are the error tuple returns just not documented for brewity?

**Comment by truemedian** [comment]
Unfortunately this is an issue with EmmyLua, as it does not allow providing separate sets of return values.

Since this is likely to become an issue eventually, I might end up switching the documentation out for something like `ldoc`, which is significantly more powerful but doesn't do any actual type resolution.

**Comment by truemedian** [comment]
For the moment, and probably the foreseeable future, I've started to use a non-standard tag `@error` to indicate the returns for an erroneous condition
